#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : devhelp
Version  : 41.1
Release  : 20
URL      : https://download.gnome.org/sources/devhelp/41/devhelp-41.1.tar.xz
Source0  : https://download.gnome.org/sources/devhelp/41/devhelp-41.1.tar.xz
Summary  : GObject-Introspection based documentation generator
Group    : Development/Tools
License  : Apache-2.0 CC-BY-SA-3.0 CC-BY-SA-4.0 CC0-1.0 GPL-3.0 GPL-3.0-or-later MIT OFL-1.1
Requires: devhelp-bin = %{version}-%{release}
Requires: devhelp-data = %{version}-%{release}
Requires: devhelp-lib = %{version}-%{release}
Requires: devhelp-license = %{version}-%{release}
Requires: devhelp-locales = %{version}-%{release}
Requires: devhelp-man = %{version}-%{release}
BuildRequires : appstream-glib
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : webkitgtk-dev

%description
For the future. The code in this directory is not compiled (but has been tested
when written of course). Instead of the code bit-rotting in a forgotten branch,
have the code on git master to ensure to have a backup. And elsewhere in the
git repo, be able to make references to the experiments done here.

%package bin
Summary: bin components for the devhelp package.
Group: Binaries
Requires: devhelp-data = %{version}-%{release}
Requires: devhelp-license = %{version}-%{release}

%description bin
bin components for the devhelp package.


%package data
Summary: data components for the devhelp package.
Group: Data

%description data
data components for the devhelp package.


%package dev
Summary: dev components for the devhelp package.
Group: Development
Requires: devhelp-lib = %{version}-%{release}
Requires: devhelp-bin = %{version}-%{release}
Requires: devhelp-data = %{version}-%{release}
Provides: devhelp-devel = %{version}-%{release}
Requires: devhelp = %{version}-%{release}

%description dev
dev components for the devhelp package.


%package doc
Summary: doc components for the devhelp package.
Group: Documentation
Requires: devhelp-man = %{version}-%{release}

%description doc
doc components for the devhelp package.


%package lib
Summary: lib components for the devhelp package.
Group: Libraries
Requires: devhelp-data = %{version}-%{release}
Requires: devhelp-license = %{version}-%{release}

%description lib
lib components for the devhelp package.


%package license
Summary: license components for the devhelp package.
Group: Default

%description license
license components for the devhelp package.


%package locales
Summary: locales components for the devhelp package.
Group: Default

%description locales
locales components for the devhelp package.


%package man
Summary: man components for the devhelp package.
Group: Default

%description man
man components for the devhelp package.


%prep
%setup -q -n devhelp-41.1
cd %{_builddir}/devhelp-41.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1632420421
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir || :

%install
mkdir -p %{buildroot}/usr/share/package-licenses/devhelp
cp %{_builddir}/devhelp-41.1/LICENSES/CC-BY-SA-4.0.txt %{buildroot}/usr/share/package-licenses/devhelp/7b3e5f0e946c0b599b04a45deebb1aaed782070d
cp %{_builddir}/devhelp-41.1/LICENSES/GPL-3.0-or-later.txt %{buildroot}/usr/share/package-licenses/devhelp/6091db0aead0d90182b93d3c0d09ba93d188f907
cp %{_builddir}/devhelp-41.1/subprojects/gi-docgen/LICENSES/Apache-2.0.txt %{buildroot}/usr/share/package-licenses/devhelp/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/devhelp-41.1/subprojects/gi-docgen/LICENSES/CC-BY-SA-3.0.txt %{buildroot}/usr/share/package-licenses/devhelp/fb41626a3005c2b6e14b8b3f5d9d0b19b5faaa51
cp %{_builddir}/devhelp-41.1/subprojects/gi-docgen/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/devhelp/8287b608d3fa40ef401339fd907ca1260c964123
cp %{_builddir}/devhelp-41.1/subprojects/gi-docgen/LICENSES/GPL-3.0-or-later.txt %{buildroot}/usr/share/package-licenses/devhelp/31a3d460bb3c7d98845187c716a30db81c44b615
cp %{_builddir}/devhelp-41.1/subprojects/gi-docgen/LICENSES/MIT.txt %{buildroot}/usr/share/package-licenses/devhelp/220906dfcc3d3b7f4e18cf8a22454c628ca0ea2e
cp %{_builddir}/devhelp-41.1/subprojects/gi-docgen/LICENSES/OFL-1.1.txt %{buildroot}/usr/share/package-licenses/devhelp/8b8a351a8476e37a2c4d398eb1e6c8403f487ea4
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang devhelp

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/devhelp

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Devhelp-3.0.typelib
/usr/share/applications/org.gnome.Devhelp.desktop
/usr/share/dbus-1/services/org.gnome.Devhelp.service
/usr/share/devhelp/assistant/assistant.css
/usr/share/devhelp/assistant/assistant.js
/usr/share/gir-1.0/*.gir
/usr/share/glib-2.0/schemas/org.gnome.devhelp.gschema.xml
/usr/share/glib-2.0/schemas/org.gnome.libdevhelp-3.gschema.xml
/usr/share/icons/hicolor/scalable/apps/org.gnome.Devhelp.svg
/usr/share/icons/hicolor/symbolic/apps/org.gnome.Devhelp-symbolic.svg
/usr/share/metainfo/org.gnome.Devhelp.appdata.xml

%files dev
%defattr(-,root,root,-)
/usr/include/devhelp-3/devhelp/devhelp.h
/usr/include/devhelp-3/devhelp/dh-application-window.h
/usr/include/devhelp-3/devhelp/dh-assistant-view.h
/usr/include/devhelp-3/devhelp/dh-book-list-builder.h
/usr/include/devhelp-3/devhelp/dh-book-list-directory.h
/usr/include/devhelp-3/devhelp/dh-book-list.h
/usr/include/devhelp-3/devhelp/dh-book-manager.h
/usr/include/devhelp-3/devhelp/dh-book-tree.h
/usr/include/devhelp-3/devhelp/dh-book.h
/usr/include/devhelp-3/devhelp/dh-completion.h
/usr/include/devhelp-3/devhelp/dh-enum-types.h
/usr/include/devhelp-3/devhelp/dh-init.h
/usr/include/devhelp-3/devhelp/dh-keyword-model.h
/usr/include/devhelp-3/devhelp/dh-link.h
/usr/include/devhelp-3/devhelp/dh-notebook.h
/usr/include/devhelp-3/devhelp/dh-profile-builder.h
/usr/include/devhelp-3/devhelp/dh-profile.h
/usr/include/devhelp-3/devhelp/dh-search-bar.h
/usr/include/devhelp-3/devhelp/dh-settings-builder.h
/usr/include/devhelp-3/devhelp/dh-settings.h
/usr/include/devhelp-3/devhelp/dh-sidebar.h
/usr/include/devhelp-3/devhelp/dh-tab-label.h
/usr/include/devhelp-3/devhelp/dh-tab.h
/usr/include/devhelp-3/devhelp/dh-web-view.h
/usr/lib64/libdevhelp-3.so
/usr/lib64/pkgconfig/libdevhelp-3.0.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/help/C/devhelp/book-format.page
/usr/share/help/C/devhelp/figures/org.gnome.Devhelp.svg
/usr/share/help/C/devhelp/index-file-format.page
/usr/share/help/C/devhelp/index.page
/usr/share/help/C/devhelp/installing-api-documentation.page
/usr/share/help/C/devhelp/search.page
/usr/share/help/ca/devhelp/book-format.page
/usr/share/help/ca/devhelp/figures/org.gnome.Devhelp.svg
/usr/share/help/ca/devhelp/index-file-format.page
/usr/share/help/ca/devhelp/index.page
/usr/share/help/ca/devhelp/installing-api-documentation.page
/usr/share/help/ca/devhelp/search.page
/usr/share/help/cs/devhelp/book-format.page
/usr/share/help/cs/devhelp/figures/org.gnome.Devhelp.svg
/usr/share/help/cs/devhelp/index-file-format.page
/usr/share/help/cs/devhelp/index.page
/usr/share/help/cs/devhelp/installing-api-documentation.page
/usr/share/help/cs/devhelp/search.page
/usr/share/help/da/devhelp/book-format.page
/usr/share/help/da/devhelp/figures/org.gnome.Devhelp.svg
/usr/share/help/da/devhelp/index-file-format.page
/usr/share/help/da/devhelp/index.page
/usr/share/help/da/devhelp/installing-api-documentation.page
/usr/share/help/da/devhelp/search.page
/usr/share/help/de/devhelp/book-format.page
/usr/share/help/de/devhelp/figures/org.gnome.Devhelp.svg
/usr/share/help/de/devhelp/index-file-format.page
/usr/share/help/de/devhelp/index.page
/usr/share/help/de/devhelp/installing-api-documentation.page
/usr/share/help/de/devhelp/search.page
/usr/share/help/es/devhelp/book-format.page
/usr/share/help/es/devhelp/figures/org.gnome.Devhelp.svg
/usr/share/help/es/devhelp/index-file-format.page
/usr/share/help/es/devhelp/index.page
/usr/share/help/es/devhelp/installing-api-documentation.page
/usr/share/help/es/devhelp/search.page
/usr/share/help/eu/devhelp/book-format.page
/usr/share/help/eu/devhelp/figures/org.gnome.Devhelp.svg
/usr/share/help/eu/devhelp/index-file-format.page
/usr/share/help/eu/devhelp/index.page
/usr/share/help/eu/devhelp/installing-api-documentation.page
/usr/share/help/eu/devhelp/search.page
/usr/share/help/fr/devhelp/book-format.page
/usr/share/help/fr/devhelp/figures/org.gnome.Devhelp.svg
/usr/share/help/fr/devhelp/index-file-format.page
/usr/share/help/fr/devhelp/index.page
/usr/share/help/fr/devhelp/installing-api-documentation.page
/usr/share/help/fr/devhelp/search.page
/usr/share/help/hr/devhelp/book-format.page
/usr/share/help/hr/devhelp/figures/org.gnome.Devhelp.svg
/usr/share/help/hr/devhelp/index-file-format.page
/usr/share/help/hr/devhelp/index.page
/usr/share/help/hr/devhelp/installing-api-documentation.page
/usr/share/help/hr/devhelp/search.page
/usr/share/help/hu/devhelp/book-format.page
/usr/share/help/hu/devhelp/figures/org.gnome.Devhelp.svg
/usr/share/help/hu/devhelp/index-file-format.page
/usr/share/help/hu/devhelp/index.page
/usr/share/help/hu/devhelp/installing-api-documentation.page
/usr/share/help/hu/devhelp/search.page
/usr/share/help/it/devhelp/book-format.page
/usr/share/help/it/devhelp/figures/org.gnome.Devhelp.svg
/usr/share/help/it/devhelp/index-file-format.page
/usr/share/help/it/devhelp/index.page
/usr/share/help/it/devhelp/installing-api-documentation.page
/usr/share/help/it/devhelp/search.page
/usr/share/help/pl/devhelp/book-format.page
/usr/share/help/pl/devhelp/figures/org.gnome.Devhelp.svg
/usr/share/help/pl/devhelp/index-file-format.page
/usr/share/help/pl/devhelp/index.page
/usr/share/help/pl/devhelp/installing-api-documentation.page
/usr/share/help/pl/devhelp/search.page
/usr/share/help/pt_BR/devhelp/book-format.page
/usr/share/help/pt_BR/devhelp/figures/org.gnome.Devhelp.svg
/usr/share/help/pt_BR/devhelp/index-file-format.page
/usr/share/help/pt_BR/devhelp/index.page
/usr/share/help/pt_BR/devhelp/installing-api-documentation.page
/usr/share/help/pt_BR/devhelp/search.page
/usr/share/help/sv/devhelp/book-format.page
/usr/share/help/sv/devhelp/figures/org.gnome.Devhelp.svg
/usr/share/help/sv/devhelp/index-file-format.page
/usr/share/help/sv/devhelp/index.page
/usr/share/help/sv/devhelp/installing-api-documentation.page
/usr/share/help/sv/devhelp/search.page
/usr/share/help/tr/devhelp/book-format.page
/usr/share/help/tr/devhelp/figures/org.gnome.Devhelp.svg
/usr/share/help/tr/devhelp/index-file-format.page
/usr/share/help/tr/devhelp/index.page
/usr/share/help/tr/devhelp/installing-api-documentation.page
/usr/share/help/tr/devhelp/search.page
/usr/share/help/uk/devhelp/book-format.page
/usr/share/help/uk/devhelp/figures/org.gnome.Devhelp.svg
/usr/share/help/uk/devhelp/index-file-format.page
/usr/share/help/uk/devhelp/index.page
/usr/share/help/uk/devhelp/installing-api-documentation.page
/usr/share/help/uk/devhelp/search.page
/usr/share/help/zh_CN/devhelp/book-format.page
/usr/share/help/zh_CN/devhelp/figures/org.gnome.Devhelp.svg
/usr/share/help/zh_CN/devhelp/index-file-format.page
/usr/share/help/zh_CN/devhelp/index.page
/usr/share/help/zh_CN/devhelp/installing-api-documentation.page
/usr/share/help/zh_CN/devhelp/search.page

%files lib
%defattr(-,root,root,-)
/usr/lib64/libdevhelp-3.so.6
/usr/lib64/libdevhelp-3.so.6.3.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/devhelp/220906dfcc3d3b7f4e18cf8a22454c628ca0ea2e
/usr/share/package-licenses/devhelp/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/devhelp/31a3d460bb3c7d98845187c716a30db81c44b615
/usr/share/package-licenses/devhelp/6091db0aead0d90182b93d3c0d09ba93d188f907
/usr/share/package-licenses/devhelp/7b3e5f0e946c0b599b04a45deebb1aaed782070d
/usr/share/package-licenses/devhelp/8287b608d3fa40ef401339fd907ca1260c964123
/usr/share/package-licenses/devhelp/8b8a351a8476e37a2c4d398eb1e6c8403f487ea4
/usr/share/package-licenses/devhelp/fb41626a3005c2b6e14b8b3f5d9d0b19b5faaa51

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/devhelp.1

%files locales -f devhelp.lang
%defattr(-,root,root,-)

