#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : devhelp
Version  : 3.36.1
Release  : 10
URL      : https://download.gnome.org/sources/devhelp/3.36/devhelp-3.36.1.tar.xz
Source0  : https://download.gnome.org/sources/devhelp/3.36/devhelp-3.36.1.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : CC-BY-SA-4.0 GPL-3.0-or-later
Requires: devhelp-bin = %{version}-%{release}
Requires: devhelp-data = %{version}-%{release}
Requires: devhelp-lib = %{version}-%{release}
Requires: devhelp-locales = %{version}-%{release}
Requires: devhelp-man = %{version}-%{release}
BuildRequires : amtk-dev
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : pkgconfig(amtk-5)
BuildRequires : pkgconfig(webkit2gtk-4.0)
BuildRequires : webkitgtk-dev

%description
Devhelp
=======
The Devhelp web page:
https://wiki.gnome.org/Apps/Devhelp
Professional services
---------------------

%package bin
Summary: bin components for the devhelp package.
Group: Binaries
Requires: devhelp-data = %{version}-%{release}

%description bin
bin components for the devhelp package.


%package data
Summary: data components for the devhelp package.
Group: Data

%description data
data components for the devhelp package.


%package dev
Summary: dev components for the devhelp package.
Group: Development
Requires: devhelp-lib = %{version}-%{release}
Requires: devhelp-bin = %{version}-%{release}
Requires: devhelp-data = %{version}-%{release}
Provides: devhelp-devel = %{version}-%{release}
Requires: devhelp = %{version}-%{release}

%description dev
dev components for the devhelp package.


%package doc
Summary: doc components for the devhelp package.
Group: Documentation
Requires: devhelp-man = %{version}-%{release}

%description doc
doc components for the devhelp package.


%package lib
Summary: lib components for the devhelp package.
Group: Libraries
Requires: devhelp-data = %{version}-%{release}

%description lib
lib components for the devhelp package.


%package locales
Summary: locales components for the devhelp package.
Group: Default

%description locales
locales components for the devhelp package.


%package man
Summary: man components for the devhelp package.
Group: Default

%description man
man components for the devhelp package.


%prep
%setup -q -n devhelp-3.36.1
cd %{_builddir}/devhelp-3.36.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1585764162
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir

%install
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang devhelp

%files
%defattr(-,root,root,-)
/usr/lib64/gedit/plugins/devhelp.plugin
/usr/lib64/gedit/plugins/devhelp.py

%files bin
%defattr(-,root,root,-)
/usr/bin/devhelp

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Devhelp-3.0.typelib
/usr/share/applications/org.gnome.Devhelp.desktop
/usr/share/dbus-1/services/org.gnome.Devhelp.service
/usr/share/devhelp/assistant/assistant.css
/usr/share/devhelp/assistant/assistant.js
/usr/share/gir-1.0/*.gir
/usr/share/glib-2.0/schemas/org.gnome.devhelp.gschema.xml
/usr/share/glib-2.0/schemas/org.gnome.libdevhelp-3.gschema.xml
/usr/share/icons/hicolor/scalable/apps/org.gnome.Devhelp.svg
/usr/share/icons/hicolor/symbolic/apps/org.gnome.Devhelp-symbolic.svg
/usr/share/metainfo/org.gnome.Devhelp.appdata.xml

%files dev
%defattr(-,root,root,-)
/usr/include/devhelp-3/devhelp/devhelp.h
/usr/include/devhelp-3/devhelp/dh-application-window.h
/usr/include/devhelp-3/devhelp/dh-assistant-view.h
/usr/include/devhelp-3/devhelp/dh-book-list-builder.h
/usr/include/devhelp-3/devhelp/dh-book-list-directory.h
/usr/include/devhelp-3/devhelp/dh-book-list.h
/usr/include/devhelp-3/devhelp/dh-book-manager.h
/usr/include/devhelp-3/devhelp/dh-book-tree.h
/usr/include/devhelp-3/devhelp/dh-book.h
/usr/include/devhelp-3/devhelp/dh-completion.h
/usr/include/devhelp-3/devhelp/dh-enum-types.h
/usr/include/devhelp-3/devhelp/dh-init.h
/usr/include/devhelp-3/devhelp/dh-keyword-model.h
/usr/include/devhelp-3/devhelp/dh-link.h
/usr/include/devhelp-3/devhelp/dh-notebook.h
/usr/include/devhelp-3/devhelp/dh-profile-builder.h
/usr/include/devhelp-3/devhelp/dh-profile.h
/usr/include/devhelp-3/devhelp/dh-search-bar.h
/usr/include/devhelp-3/devhelp/dh-settings-builder.h
/usr/include/devhelp-3/devhelp/dh-settings.h
/usr/include/devhelp-3/devhelp/dh-sidebar.h
/usr/include/devhelp-3/devhelp/dh-tab-label.h
/usr/include/devhelp-3/devhelp/dh-tab.h
/usr/include/devhelp-3/devhelp/dh-web-view.h
/usr/lib64/libdevhelp-3.so
/usr/lib64/pkgconfig/libdevhelp-3.0.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/help/C/devhelp/book-format.page
/usr/share/help/C/devhelp/index-file-format.page
/usr/share/help/C/devhelp/index.page
/usr/share/help/C/devhelp/installing-api-documentation.page
/usr/share/help/C/devhelp/search.page
/usr/share/help/cs/devhelp/book-format.page
/usr/share/help/cs/devhelp/index-file-format.page
/usr/share/help/cs/devhelp/index.page
/usr/share/help/cs/devhelp/installing-api-documentation.page
/usr/share/help/cs/devhelp/search.page
/usr/share/help/de/devhelp/book-format.page
/usr/share/help/de/devhelp/index-file-format.page
/usr/share/help/de/devhelp/index.page
/usr/share/help/de/devhelp/installing-api-documentation.page
/usr/share/help/de/devhelp/search.page
/usr/share/help/es/devhelp/book-format.page
/usr/share/help/es/devhelp/index-file-format.page
/usr/share/help/es/devhelp/index.page
/usr/share/help/es/devhelp/installing-api-documentation.page
/usr/share/help/es/devhelp/search.page
/usr/share/help/fr/devhelp/book-format.page
/usr/share/help/fr/devhelp/index-file-format.page
/usr/share/help/fr/devhelp/index.page
/usr/share/help/fr/devhelp/installing-api-documentation.page
/usr/share/help/fr/devhelp/search.page
/usr/share/help/hr/devhelp/book-format.page
/usr/share/help/hr/devhelp/index-file-format.page
/usr/share/help/hr/devhelp/index.page
/usr/share/help/hr/devhelp/installing-api-documentation.page
/usr/share/help/hr/devhelp/search.page
/usr/share/help/hu/devhelp/book-format.page
/usr/share/help/hu/devhelp/index-file-format.page
/usr/share/help/hu/devhelp/index.page
/usr/share/help/hu/devhelp/installing-api-documentation.page
/usr/share/help/hu/devhelp/search.page
/usr/share/help/it/devhelp/book-format.page
/usr/share/help/it/devhelp/index-file-format.page
/usr/share/help/it/devhelp/index.page
/usr/share/help/it/devhelp/installing-api-documentation.page
/usr/share/help/it/devhelp/search.page
/usr/share/help/pl/devhelp/book-format.page
/usr/share/help/pl/devhelp/index-file-format.page
/usr/share/help/pl/devhelp/index.page
/usr/share/help/pl/devhelp/installing-api-documentation.page
/usr/share/help/pl/devhelp/search.page
/usr/share/help/pt_BR/devhelp/book-format.page
/usr/share/help/pt_BR/devhelp/index-file-format.page
/usr/share/help/pt_BR/devhelp/index.page
/usr/share/help/pt_BR/devhelp/installing-api-documentation.page
/usr/share/help/pt_BR/devhelp/search.page
/usr/share/help/sv/devhelp/book-format.page
/usr/share/help/sv/devhelp/index-file-format.page
/usr/share/help/sv/devhelp/index.page
/usr/share/help/sv/devhelp/installing-api-documentation.page
/usr/share/help/sv/devhelp/search.page

%files lib
%defattr(-,root,root,-)
/usr/lib64/libdevhelp-3.so.6
/usr/lib64/libdevhelp-3.so.6.2.0

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/devhelp.1

%files locales -f devhelp.lang
%defattr(-,root,root,-)

